version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "./Dockerfiles/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./Dockerfiles/mysql/conf.d:/etc/mysql/conf.d"
  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
      - .:/app
      - bundle_cache:/bundle
      # Map bundle cache to named volume
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle_cache:
  # Mount volume with default driver
